config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # require 'sidekiq/web'
  # mount Sidekiq::Web => "/sidkiq"
  
  root to: "home#index"


  resources :restaurants do
    resources :reviews, only: [:create, :destroy, :new]
    resources :menus
      collection do
        get :search , :google_map
      end
      member do
        post :rest_sortable
      end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :subscriptions
  post "/card" => "subscriptions#create_card", as: :create_payment_method
  post 'subscribe' => 'subscriptions#subscribe', as: :subscribe
  
  get '/card/new' => 'subscriptions#new_card', as: :add_payment_method

  get 'success' => 'subscriptions#success', as: :success

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

   def initialize(user)
      user ||= User.new
      if user.owner? 
        can :manage, Restaurant, user_id: user.id
      else
        can :read, Restaurant
      end
   
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
      
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :restaurant_categories
    has_many :restaurants, through: :restaurant_categories 
end


 

app/models/menu.rb
class Menu < ApplicationRecord
    belongs_to :restaurant
    has_many_attached :pictures
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

    searchable do
        text :name, :description, :full_address
        string  :sort_full_address do
            full_address.downcase.gsub(/^(an?|the)/, '')
        end
    end
    
    has_many :restaurant_categories
    has_many :categories, through: :restaurant_categories
    has_one_attached :image 
    has_many :restaurant_images, inverse_of: :restaurant
    has_many_attached :images
    has_many_attached :clips 
    has_many :reviews
    has_many :menus
    belongs_to :user, optional: true
    
    # validates :name, presence: true
    # validates :email, presence: true
    # validates :contact, presence: true
    # validates :full_address, presence: true

    resourcify
end

app/models/restaurant_category.rb
class RestaurantCategory < ApplicationRecord
    belongs_to :restaurant
    belongs_to :category
end

app/models/restaurant_image.rb
class RestaurantImage < ApplicationRecord
    belongs_to :restaurant
    has_one_attached :image
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :restaurant
    belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  
  belongs_to :resource,
             :polymorphic => true,
             :optional =>true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_one_attached :image   

  has_many :restaurants
  has_many :reviews   
  
  def owner?
    has_role?(:owner)
  end
  
  def normal_user?
    has_role?(:normal_user)
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @restaurants = Restaurant.all  

    if current_user.has_role? :owner 
      if current_user.stripe_id.nil? 
        redirect_to subscriptions_path
      else
        redirect_to restaurants_path
      end    
    end 
  end
end

app/controllers/menus_controller.rb
class MenusController < ApplicationController
    before_action :authenticate_user!

    def index
        @restaurant = Restaurant.find(params[:restaurant_id])
        @menus = Menu.order(position: :desc)
    end

    def new
        @restaurant = Restaurant.find(params[:restaurant_id])
        @menu = @restaurant.menus.build
    end

    def show
        @restaurant = Restaurant.find(params[:restaurant_id])
        @menu = @restaurant.menus.find(params[:id])
    end 

    def edit
        @restaurant = Restaurant.find(params[:restaurant_id])
        @menu = @restaurant.menus.find(params[:id])
    end

    def create
        @restaurant = Restaurant.find(params[:restaurant_id])  
        @menu = @restaurant.menus.create(menu_params)
        @menu.save
          redirect_to restaurant_menus_path
        
    end

    def update
        if @menu.update_attributes(menu_params)
            redirect_to restaurant_menus_path
        else
        render action: 'edit'
        end
    end 

    def destroy
        @restaurant = Restaurant.find(params[:restaurant_id]) 
        @menu = Menu.find(params[:id])
        @menu.destroy 
          redirect_to restaurant_menus_path

    end

    private 

    def menu_params
        params.require(:menu).permit(:title, :position, :description, :pricing, pictures: [])
    end
    
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def create
      @restaurant = Restaurant.find(params[:restaurant_id])
      @review = @restaurant.reviews.new(review_params)
      @review.user_id = current_user.id
      @review.save
      HardWorker.perform_async(current_user.id, @review.id,  @restaurant.id)   
    end

    def destroy
      @restaurant = Restaurant.find(params[:restaurant_id])
      @review = @restaurant.reviews.find(params[:id])
      @review.destroy 
       
    end

    private
    def review_params
        params.require(:review).permit(:title, :description, :rating)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurant_image_helper.rb
module RestaurantImageHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/menus/_form.html.erb
<div class="modal-body">
  <%= form_with model: [ @restaurant, @restaurant.menus.build] do |f| %>

   <div class="mb-3">   
     <%= f.label :Photo, class: "form-label" %>
     <%= f.file_field :pictures,  multiple: true, class: "form-control" %> 
   </div> 
     
    <div class="form-group" >
      <%= f.label :Title %><br>
      <%= f.text_field :title, class: "form-control" %>
    </div>

    <div class="form-group" >
      <%= f.label :Description %><br>
      <%= f.text_area :description, class: "form-control" %>
    </div>

    <div class="form-group" >
      <%= f.label :Pricing %><br>
      <%= f.text_field :pricing, class: "form-control" %>
    </div>

    <div class="modal-footer">
      <%= f.submit "save", class: "btn btn-primary" %>
    </div>
 
  <% end %>  

</div>

app/views/menus/_index.html.erb
<div id="sortable1">
    <% @restaurant.menus.each do |menu| %>   
        <div class="card mb-3 rounded shadow p-2" style="max-width: 540px;">
            <div class="row justify-content-center">
                <div class="col-2 mt-2">
                    <% menu.pictures.first(1).each do |picture| %>              
                        <% if menu.pictures.attached? %>             
                            <%= image_tag(url_for(picture), height: '80px', width: '80px', class: "card-img-top image" ) %> 
                        <% else %>
                            <%= image_tag "karly-gomez-lK1Q5RyD6tc-unsplash.jpg", height: "150px", class: "card-img-top image" %>
                        <% end %>  
                    <% end %>  
                </div> 
                    
                <div class="col-6">
                    <div class="card-body">
                    <h5 class="card-title text fw-bold"><%= menu.title %></h5>
                    <p class="card-text text "><small class="text-muted"><%= menu.description %></small></p> 
                    <p class="card-text text"><%= menu.pricing %></p>
                    </div>          
                </div>
                

                <div class="col mt-2">
                    <div class="card-body">
                    <%= link_to restaurant_menu_path(@restaurant, menu.id), class: "btn btn-outline-danger mt-4", data: { confirm: "Are you sure "} do %>
                        <i class="fa-solid fa-trash"></i>
                    <% end %>
                    
                    <%= link_to edit_restaurant_menu_path(@restaurant, menu.id), class: "btn btn-outline-info mt-4" do %>
                        <i class="fa-solid fa-file-pen"></i> 
                    <% end %> 
                    </div>
                </div>  
            </div>
        </div>
    <% end %>  
</div>

  <script> 
    $("#sortable1").sortable({
        stop: function(e, ui) {
                $.ajax({
                url: $(this).data("url"),
                type: "PATCH",
                data: $(this).sortable('serialize'),
            });
        }
    });
   </script>       

app/views/menus/_show.html.erb
<br>
<br>

<div class="modal-body">
  <div class="container">      
    <div class="col-4">
      <% @restaurant.menus.each do |menu| %>   
        <figure>    
          <% menu.pictures.each do |picture| %>              
            <div class="card shadow rounded mb-3" style="width: 50rem;">
              <% if menu.pictures.attached? %>             
                  <%= image_tag(url_for(picture), height: "250px", class: "card-img-top image" ) %> 
              <% else %>
                  <%= image_tag "karly-gomez-lK1Q5RyD6tc-unsplash.jpg", height: "150px", class: "card-img-top image" %>
              <% end %>  
            
              <div class="card-body overlay">
                <h5 class="card-title text fw-bold"><%= menu.title %></h5>
                <p class="card-text text "><small class="text-muted"><%= menu.description %></small></p> 
                <p class="card-text text"><%= menu.pricing %></p>
    
              </div>
            </div>
          <% end %>    
        </figure> 
      <% end %>   
    </div>
  </div>
</div>





                           
                 
               

app/views/menus/edit.html.erb
<br/>
<h2>edit Menu</h2>

<%= render "form",  menu: @restaurant %>

app/views/menus/index.html.erb
<br>
<br>

<div class="container-md " >
    <div class="row">
        <div class="col-12">
          <%= link_to "New Menu", new_restaurant_menu_path, class: "btn btn-outline-primary " %>
          <br/>
          <br/>
        </div>

        <div class="col-8 ", id="newRestaurant">  
          <%= render "index", menus: @menus %>   
        </div>
    </div>
</div>

app/views/menus/new.html.erb
<br/>
<h2>New Menu</h2>
<%= render "form",  menu: @restaurant %>