config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # require 'sidekiq/web'
  # mount Sidekiq::Web => "/sidkiq"
  
  root to: "home#index"


  resources :restaurants do
    resources :reviews, only: [:create, :destroy, :new]
    resources :menus
      collection do
        get :search , :google_map
      end
      member do
        post :rest_sortable
      end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :subscriptions
  post "/card" => "subscriptions#create_card", as: :create_payment_method
  post 'subscribe' => 'subscriptions#subscribe', as: :subscribe
  
  get '/card/new' => 'subscriptions#new_card', as: :add_payment_method

  get 'success' => 'subscriptions#success', as: :success

end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

   def initialize(user)
      user ||= User.new
      if user.owner? 
        can :manage, Restaurant, user_id: user.id
      else
        can :read, Restaurant
      end
   
    # Define abilities for the user here. For example:
    #
    #   return unless user.present?
    #   can :read, :all
    #   return unless user.admin?
    #   can :manage, :all
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, published: true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/blob/develop/docs/define_check_abilities.md
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
      
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
    has_many :restaurant_categories
    has_many :restaurants, through: :restaurant_categories 
end


 

app/models/menu.rb
class Menu < ApplicationRecord
    belongs_to :restaurant
    has_many_attached :pictures
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

    searchable do
        text :name, :description, :full_address
        string  :sort_full_address do
            full_address.downcase.gsub(/^(an?|the)/, '')
        end
    end
    
    has_many :restaurant_categories
    has_many :categories, through: :restaurant_categories
    has_one_attached :image 
    has_many :restaurant_images, inverse_of: :restaurant
    has_many_attached :images
    has_many_attached :clips 
    has_many :reviews
    has_many :menus
    belongs_to :user, optional: true
    
    # validates :name, presence: true
    # validates :email, presence: true
    # validates :contact, presence: true
    # validates :full_address, presence: true

    resourcify
end

app/models/restaurant_category.rb
class RestaurantCategory < ApplicationRecord
    belongs_to :restaurant
    belongs_to :category
end

app/models/restaurant_image.rb
class RestaurantImage < ApplicationRecord
    belongs_to :restaurant
    has_one_attached :image
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :restaurant
    belongs_to :user
end

app/models/role.rb
class Role < ApplicationRecord
  has_and_belongs_to_many :users, :join_table => :users_roles

  
  belongs_to :resource,
             :polymorphic => true,
             :optional =>true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable

  has_one_attached :image   

  has_many :restaurants
  has_many :reviews   
  
  def owner?
    has_role?(:owner)
  end
  
  def normal_user?
    has_role?(:normal_user)
  end 
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @restaurants = Restaurant.all  

    if current_user.has_role? :owner 
      if current_user.stripe_id.nil? 
        redirect_to subscriptions_path
      else
        redirect_to restaurants_path
      end    
    end 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/menu_helper.rb
module MenuHelper
end

app/helpers/menus_helper.rb
module MenusHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyRestaurant</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    
    <link rel="stylesheet" href="//netdna.bootstrapcdn.com/bootstrap/3.0.0/css/bootstrap-glyphicons.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'https://checkout.stripe.com/checkout.js' %>

     <script
    src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDiHu2NfKlUSaE0-nluvepwIg5TpBdT-8c &callback=initMap&v=weekly"
    defer
    ></script>
    
     <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
     <script src="https://code.jquery.com/ui/1.13.1/jquery-ui.js"></script>

  </head>

  <body> 
    <% if controller_name == "restaurants" && action_name == "show" || action_name == "search" || action_name == "google_map" %>

    <% else %>
      <%= render "shared/header" %>
    <% end %> 

    <% flash.each do |type, msg| %>
      <div class="alert alert-info">
        <%= msg %>
      </div>
    <% end %> 

    <%= yield %>
    <%= render "shared/footer" %>
  </body>


</html>

app/views/shared/_header.html.erb
 <section class="header">
     <div class="container-fluid">
          
        <nav class="navbar navbar-expand-lg navbar-dark">
        <div class="container-fluid">
       
          <a class="navbar-brand" href="#">MyRestaurant</a>
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
              <li class="nav-item">
                <a class="nav-link act" aria-current="page" href="/">Home</a>
              </li>

              <li class="nav-item">
                <%= link_to "Restaurant", restaurants_path, class: "nav-link" %>
              </li>

              <% if user_signed_in? %>
              <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  <%= current_user.email %>    
                </a>
                <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                   <% if current_user.has_role? :owner %>
                      <%= link_to "Add Restaurant", new_restaurant_path, class: "text-decoration-none text-reset dropdown-item", remote: true %>
                      <% if current_user.stripe_id.nil? %>
                        <%= link_to "Subscription", add_payment_method_path, remote: true, class: "dropdown-item" %>
                      <% end %>
                    <% end %>
                    <%= link_to "log out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
                </ul>
              </li>
              <% else %>
                  <%= link_to "Sign up", new_registration_path(resource_name), class: "nav-link" %><br />
                  <%= link_to "Log in", new_session_path(resource_name), class: "nav-link" %><br />
              <% end %>    
            </ul>    
          </div>
        </div>
      </nav>

      <br/>
      <br/>            
       <div class="middle d-flex justify-content-center mt-5">
          <h1 class="text-white fw-bold">Shine</h1>
       </div>
        <p class="text-white middleText d-flex justify-content-center ">Welcome to<span class="theme-text"> The Shine</span></p> 
        <% if controller_name == "home" && action_name == "index"  %>
          <div class="d-flex justify-content-center search">     
            <%= form_tag(search_restaurants_path, method: :get, class: "d-flex", role: "search", type: "text") do %>
        
             <%= text_field_tag(:search, params[:search], class: "form-control me-2", id: "searchForm" , placeholder: "Search for restaurant, dish, or cuisine" ) %>
           
              <i class="fa-solid fa-magnifying-glass fa-2x me-2" id="searchBar"></i>  
        
              <%= submit_tag "search", class: "btn btn-dark btn-lg" %>   
                
            <% end %> 
          </div>
        <% end %>   
     </div>
   
  </section>
  
                     