config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # require 'sidekiq/web'
  # mount Sidekiq::Web => "/sidkiq"
  
  root to: "home#index"


  resources :restaurants do
    resources :reviews, only: [:create, :destroy, :new]
    resources :menus
      collection do
        get :search , :google_map
      end
      member do
        post :rest_sortable
      end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :subscriptions
  post "/card" => "subscriptions#create_card", as: :create_payment_method
  post 'subscribe' => 'subscriptions#subscribe', as: :subscribe
  
  get '/card/new' => 'subscriptions#new_card', as: :add_payment_method

  get 'success' => 'subscriptions#success', as: :success

end

app/models/subscription.rb
class Subscription < ApplicationRecord
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController
  before_action :authenticate_user!

  require "stripe"

    def index
      @user=current_user.email
    end
    
    def success
      @plans = Stripe::Plan.list.data
    end
    
    def new_card
      respond_to do |format|
        format.js
      end
    end

    def create_card 
      respond_to do |format|
        if current_user.stripe_id.nil?
          customer = Stripe::Customer.create({"email": current_user.email}) 
          current_user.update(:stripe_id => customer.id)
        end
  
        card_token = params[:stripeToken]
        if card_token.nil?
          format.html { redirect_to billing_path, error: "Oops"}
        end
  
        customer = Stripe::Customer.new current_user.stripe_id
        customer.source = card_token
        customer.save
  
        format.html { redirect_to success_path }
      end
    end

    def subscribe
      if current_user.stripe_id.nil?
        redirect_to success_path, :flash => {:error => 'Firstly you need to enter your card'}
        return
      end

      customer = Stripe::Customer.new current_user.stripe_id

      subscriptions = Stripe::Subscription.list(customer: customer.id)
      subscriptions.each do |subscription|
        subscription.delete
      end

      plan_id = params[:plan_id]
      subscription = Stripe::Subscription.create({
                                                     customer: customer,
                                                     items: [{plan: plan_id}], })

      subscription.save
      redirect_to restaurants_path
    end

    def create_card 
      respond_to do |format|
        if current_user.stripe_id.nil?
          customer = Stripe::Customer.create({"email": current_user.email}) 
          current_user.update(:stripe_id => customer.id)
        end
  
        card_token = params[:stripeToken]
        if card_token.nil?
          format.html { redirect_to subscriptions_path, error: "Oops"}
        end
  
        customer = Stripe::Customer.new current_user.stripe_id
        customer.source = card_token
        customer.save
  
        format.html { redirect_to success_path }
      end
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/subscriptions/index.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4 text-center">
      <h1> Welcome  <%= @user %></h1>
    </div>
  </div>

  <div class="row">
    <h2 class="col-md-12 mt-5 text-center">
      Are you ready to pay?

    </h2>
  </div>
</div>

<div class="container mt-2">
    <div class="row h-100 justify-content-center align-items-center">
        <div class="col-md-2 ">
          <div class="card shadow">
          <%= form_tag create_payment_method_path, id: "billing-create-payment-method" do  %>   
            <%= link_to "Add Card Detail", add_payment_method_path, remote: true, class: "btn btn-primary" %>
          <% end %>
          </div>
        </div>
    </div>
</div>    

app/views/subscriptions/new_card.js.erb
var handler = StripeCheckout.configure({
    key: 'pk_test_51LGFgaSDRTplecUgk4lWsw5gzcaPfpmQOynBfh8tTHNuV5MvpHEmJRKD7KP8omnosAdoCMC7OB9K3mXpC8aYOCRF00De7m6Cfa',
    //get a publishable key that we put in editor depending on environment: production or development
    locale: 'auto',
    //handle translation
    name: "upload.express",
    description: "Add your credit card information",
    email: "<%= current_user.email %>",
    panelLabel: "Add payment method",
    allowRememberMe: false,
    token: function (token) {
        var form = document.getElementById('billing-create-payment-method');
        //we will create element with this id in the next step
        var hiddenInput = document.createElement('input');
        hiddenInput.setAttribute('type', 'hidden');
        hiddenInput.setAttribute('name', 'stripeToken');
        hiddenInput.setAttribute('value', token.id);
        //creating an <input type="hidden" name="stripeToken" value="<id>"/>. We will need this information in the next steps to link a user to his card 
        form.appendChild(hiddenInput);
        //adding this input when we use a form.
        form.submit();
    }
});

handler.open();

window.addEventListener('popstate', function() {
    handler.close();
});

app/views/subscriptions/subscription_checkout.html.erb
<div class="plan-container">
  <ul>
    <% @plans.each do |plan| %>
      <li class="plan">
        <div class="header">
          <%= plan[:name] %>
        </div>
        <div class="price">
          <%= (plan[:amount]/100) %>
        </div>
        <%= form_tag('/subscription_checkout', {method: :post, plan: plan}) do %>
          <input name="plan_id" type="hidden" value="<%= plan[:id] %>">
          <script class="stripe-button" data-amount="<%= (plan[:amount]) %>" data-currency="<%= plan[:currency] %>" data-email="customer@example.com" data-image="/assets/sitepoint.png" data-key="<%= Rails.configuration.stripe[:publishable_key] %>" src="https://checkout.stripe.com/checkout.js"></script>
        <% end %>
      </li>
    <% end %>
  </ul>
</div>

app/views/subscriptions/success.html.erb
<div class="container">
  <div class="row">
    <div class="col-md-12 mt-4 text-center">
      <h2>You successfully linked a credit card to your account</h2>
    </div>
  </div>
</div>

<div class="row">
  <div class="col-md-12 mt-3 text-center">
    <h3>Now you need to choose your plan</h3>
  </div>
</div>
<!-- creating a form -->
<%=form_tag subscribe_path, method: :post do %>
<div class="row">
  <div class="col-md-4"></div>
  <div class="col-md-4 text-center">
    <div class="form-group">
      <select class="form-control" name="plan_id">
        <% @plans.each do |plan| %>
        <option value="<%= plan.id %>"><%= plan.amount/100 %>/€ <%= plan.nickname %></option>
        <!-- we pass id chosen by custmer as a value  to use it for subscription -->
        <%end%>
      </select>
    </div>
  </div>
  <div class="col-md-4"></div>
</div>
<div class="row">
  <div class="col-md-12 mt-2 text-center">
    <%= submit_tag 'Save changes', class: "btn btn-primary" %>
  </div>
</div>
<% end %>