config/routes.rb
Rails.application.routes.draw do

  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  # require 'sidekiq/web'
  # mount Sidekiq::Web => "/sidkiq"
  
  root to: "home#index"


  resources :restaurants do
    resources :reviews, only: [:create, :destroy, :new]
    resources :menus
      collection do
        get :search , :google_map
      end
      member do
        post :rest_sortable
      end
  end

  devise_for :users, controllers: { registrations: 'users/registrations' }

  resources :subscriptions
  post "/card" => "subscriptions#create_card", as: :create_payment_method
  post 'subscribe' => 'subscriptions#subscribe', as: :subscribe
  
  get '/card/new' => 'subscriptions#new_card', as: :add_payment_method

  get 'success' => 'subscriptions#success', as: :success

end

app/models/restaurant.rb
class Restaurant < ApplicationRecord

    searchable do
        text :name, :description, :full_address
        string  :sort_full_address do
            full_address.downcase.gsub(/^(an?|the)/, '')
        end
    end
    
    has_many :restaurant_categories
    has_many :categories, through: :restaurant_categories
    has_one_attached :image 
    has_many :restaurant_images, inverse_of: :restaurant
    has_many_attached :images
    has_many_attached :clips 
    has_many :reviews
    has_many :menus
    belongs_to :user, optional: true
    
    # validates :name, presence: true
    # validates :email, presence: true
    # validates :contact, presence: true
    # validates :full_address, presence: true

    resourcify
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:show]

  def index
    @restaurants = current_user.restaurants.order(position: :desc)      
  end

  def edit
    @restaurant = current_user.restaurants.find(params[:id])
  end

  def new
    @restaurant = current_user.restaurants.build
    @restaurant.restaurant_images.build
  end

  def rest_sortable
    @restaurant = Restaurant.find(params[:id])
    @restaurant.each_with_index do |id, index|
      Restaurant.where(id: id).update_all(position: index + 1)
    end  
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    authorize! :read, @restaurant
  end

  def create
    @user = current_user
    @restaurant = @user.restaurants.create(restaurant_params)
    @restaurant.save
    @restaurants = current_user.restaurants
    params[:restaurant][:category_ids].each do |category|
      if category.present?
        @restaurant.restaurant_categories.create(category_id: category)
      end
    end
    flash.now[:notice] = "Restaurant was successfully created"
    respond_to do |format|
      format.js
    end  
  end

  def update
    @restaurant = current_user.restaurants.find(params[:id])
    @restaurant.update(restaurant_params)
    @restaurants = current_user.restaurants
    params[:restaurant][:category_ids].each do |category|
      if category.present?
        @restaurant.restaurant_categories.create(category_id: category)
      end
    end
      respond_to do |format|
        format.js
      end
  end

  def destroy
    @restaurant = current_user.restaurants.find(params[:id])
    @restaurant.destroy
  end

  def search
    @search = Restaurant.search do
      fulltext  params[:search]
    end
    @restaurants = @search.results
  end

  def google_map

  end 

  private
   
  def restaurant_params
    params.require(:restaurant).permit(:name, :position, :latitude, :longitude, :description, :image, :email, :contact, :full_address, clips: [], images: [] )
  end
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/views/restaurants/_form.html.erb
<div class= "mb-3 shadow">
<%= form_for @restaurant, remote: true do |f| %>
<div class="border p-4">
    <div class="mb-3">
      <%= f.label :logo,class: "form-label" %>
      <%= f.file_field :image, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :name, class: "form-label"%>
      <%= f.text_field :name, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :description, class: "form-label"%>
      <%= f.text_field :description, class: "form-control"%>
    </div>

    <div class="mb-3">
      <%= f.label :email, class: "form-label" %>
      <%= f.text_field :email, class: "form-control" %>
    </div>

    <div class="mb-3">
      <%= f.label :contact, class: "form-label" %>
      <%= f.text_field :contact, class: "form-control" %>
    </div>

    <div class="mb-3">                     
      <%= f.hidden_field :latitude, class: 'form-control', data: { maps_target: "latitude" }%>
    </div>

    <div class="mb-3">              
      <%= f.hidden_field  :longitude, class: 'form-control', data: { maps_target: "longitude" } %>
    </div>

    <div class="mb-3">
        <%= f.label :category %>
        <%= f.select :category_ids, Category.pluck(:name, :id), { :prompt => "Please select"}, class: 'form-control', multiple: true %> 
    </div>
  
    <div class="mb-3">
      <%= f.label :full_address, class: "form-label" %>
      <%= f.text_field :full_address, class: "form-control" %>
    </div>

   <div class="mb-3">   
     <%= f.label :Photo, class: "form-label" %>
     <%= f.file_field :images, multiple: true ,class: "form-control" %> 
   </div>  


   <div class="mb-3">   
     <%= f.label :Video, class: "form-label" %>
     <%= f.file_field :clips, multiple: true, class: "form-control" %> 
   </div> 

    <div class="actions" >
      <%= f.submit "submit", class: "btn btn-outline-dark "  %>
    </div>
</div>
<% end %>
</div>

app/views/restaurants/_index.html.erb
      
   <div id="sortable1">
    <% @restaurants.each do |restaurant| %> 
        <div id="restaurantForm_<%= restaurant.id %>">
            <%= render "restaurant", restaurant: restaurant %>
        </div>  
    <% end %> 
   </div>
    
   
    <script>
        $("#sortable1").sortable({
        stop: function(e, ui) {
            debugger
            $.ajax({
            beforeSend: function(xhr) {xhr.setRequestHeader('X-CSRF-Token', $('meta[name="csrf-token"]').attr('content'))},
            url: $(this).data('restaurants/rest_sortable(@restaurant)'),
            type: 'post',
            format: 'js'
          })
            }
        });
    </script>



  

app/views/restaurants/_restaurant.html.erb
 
 
    <div class="card mb-3 rounded shadow p-2" style="max-width: 540px;">
        <div class="row justify-content-center">
            <div class="col-2">
                <% if restaurant.image.attached? %>
                    <%= image_tag restaurant.image, height: '80px', width: '80px' %>
                <% else %>
                    <img src="..." class="img-fluid rounded-start" alt="...">
                <% end %>  
            </div>

            <div class="col-6">
                <div class="card-body">
                  
                  <h6><%= link_to restaurant.name, restaurant_path(restaurant), class: "text-decoration-none text-reset fw-bold" %></h6>
                
                </div>
            </div>

            <div class="col mt-2">
                <div class="card-body">
                  
                    <%= link_to edit_restaurant_path(restaurant), class: "btn btn-outline-dark mt-2 actions", remote: true do %>
                       <i class="fa-solid fa-pen-clip "></i>
                    <% end %>
                 
                    <%= link_to restaurant, method: :delete, data: { confirm: "Are you sure "}, class: "btn btn-outline-danger mt-2 actions", remote: true do %>
                      <i class="fa-solid fa-trash"></i>
                    <% end %>
                 
                </div>
            </div>
        </div>
    </div>

app/views/restaurants/create.js.erb
$("#newRestaurant").html("<%= j (render "index", restaurants: @restaurants) %>")

app/views/restaurants/destroy.js.erb
$("#restaurantForm_<%= @restaurant.id %>").remove();

app/views/restaurants/edit.js.erb
$("#newRestaurant").html("<%= j (render "form", restaurant: @restaurant ) %>")

app/views/restaurants/google_map.html.erb
<br/>
<br/>


<html>
  <head>
    <title>Place Autocomplete</title>
    <script src="https://polyfill.io/v3/polyfill.min.js?features=default"></script>
    <!-- jsFiddle will insert css and js -->
  </head>
  <body>
    <div class="pac-card" id="pac-card">
      <div>
        <div id="title">Autocomplete search</div>
        <div id="type-selector" class="pac-controls">
          <input
            type="radio"
            name="type"
            id="changetype-all"
            checked="checked"
          />
          <label for="changetype-all">All</label>

          <input type="radio" name="type" id="changetype-establishment" />
          <label for="changetype-establishment">establishment</label>

          <input type="radio" name="type" id="changetype-address" />
          <label for="changetype-address">address</label>

          <input type="radio" name="type" id="changetype-geocode" />
          <label for="changetype-geocode">geocode</label>

          <input type="radio" name="type" id="changetype-cities" />
          <label for="changetype-cities">(cities)</label>

          <input type="radio" name="type" id="changetype-regions" />
          <label for="changetype-regions">(regions)</label>
        </div>
        <br />
        <div id="strict-bounds-selector" class="pac-controls">
          <input type="checkbox" id="use-location-bias" value="" checked />
          <label for="use-location-bias">Bias to map viewport</label>

          <input type="checkbox" id="use-strict-bounds" value="" />
          <label for="use-strict-bounds">Strict bounds</label>
        </div>
      </div>
      <div id="pac-container">
        <input id="pac-input" type="text" placeholder="Enter a location" />
      </div>
    </div>
    <div id="map"></div>
    <div id="infowindow-content">
      <span id="place-name" class="title"></span><br />
      <span id="place-address"></span>
    </div>

    <!-- 
     The `defer` attribute causes the callback to execute after the full HTML
     document has been parsed. For non-blocking uses, avoiding race conditions,
     and consistent behavior across browsers, consider loading using Promises
     with https://www.npmjs.com/package/@googlemaps/js-api-loader.
    -->
    <script
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyDiHu2NfKlUSaE0-nluvepwIg5TpBdT-8c&callback=initMap&libraries=places&v=weekly"
      defer
    ></script>
  </body>
</html>

 
   

app/views/restaurants/index.html.erb
<br>
<br>

<div class="container-md" >
    <div class="row">
        <div class="col-4">
            <% if current_user.has_role? :owner %>
                <div class="card shadow " style="width: 18rem;">
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item"><span class="fas fa-edit orange"></span> &nbsp;</i><%= link_to "Add Restaurant", new_restaurant_path, class: "text-decoration-none text-reset fw-bold", remote: true %></li>
                         <% if current_user.stripe_id.nil? %>
                            <li class="list-group-item">
                                <span class="fas fa-dollar-sign orange"></span> &nbsp;<%= link_to "Subscription", add_payment_method_path, remote: true, class: "text-decoration-none text-reset fw-bold" %></i>
                            </li>
                         <% end %>
                        <li class="list-group-item">Reset Passsword</li>
                        <li class="list-group-item">My Profile</li>
                        <li class="list-group-item"><span class="fas fa-sign-out-alt orange"></span> &nbsp;<%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "text-decoration-none text-reset fw-bold" %></i></li>
                    </ul>
                </div>
            <% end %>
        </div>
        
        <div class="col-8 ", id="newRestaurant">
            <%= render "index", restaurants: @restaurants %>   
        </div>
    </div>
</div>

app/views/restaurants/index.js.erb
$("#restaurantForm").html("<%= j render "index" %>")

app/views/restaurants/new.js.erb
$("#newRestaurant").html("<%= j (render "form",  restaurant: @restaurant ) %>")

app/views/restaurants/search.html.erb
<br>
<br>
              
<div class="container-md" >
    <div class="row row-cols-1 row-cols-md-4 g-4  hover01 column">
        <% @restaurants.each do |restaurant| %>   
          <figure> 
          
            <div class="col" style="height: 30%;">
                <div class="card shadow rounded">
                    <% if restaurant.image.attached? %>  
                        <%= link_to restaurant_path(restaurant), class: "text-decoration-none text-reset" do %>
                          <%= image_tag restaurant.image, height: "150px", class: "card-img-top image" %> 
                        <% end %>   
                    <% end %>  
            
                    <div class="card-body overlay">
                        <h5 class="card-title text fw-bold"><%= restaurant.name %></h5>
                        <p class="card-text text "><small class="text-muted"><%= restaurant.full_address %></small></p>
                      
                        <%= restaurant.reviews.average(:rating) do %>
                          <span class="glyphicon glyphicon-star" aria-hidden="true"></span>           
                        <% end %>
                       
                    </div>
                </div>  
            </div>
       
          </figure> 
        <% end %>   
    </div>
</div>  

app/views/restaurants/show.html.erb
<div class="container mt-3">
  <!-----------------------------slideshow carousel---------------------------->
  <div id="demo<%= @restaurant.id %>" class="carousel slide carousel-fade" data-bs-ride="carousel">
    <div class="carousel-inner">
      
        <% @restaurant.images.each_with_index do |image, index| %>              
          <% if @restaurant.images.attached? %>             
            <div class="carousel-item <%= "active" if index == 0 %>">   
              <%= image_tag(url_for(image), style: "width:100%; height:600px" ) %>
            </div>
          <% end %>  
        <% end %>
      
        <% @restaurant.clips.each_with_index do |clip, index| %>               
            <% if @restaurant.clips.attached? %>  
              <div class="carousel-item <%= "active" if index == 0 && @restaurant.images.blank? %>">
                <%= video_tag(url_for(clip), style:"width:100%; height:600px", controls: '') %>
              </div>
            <% end %>           
        <% end %> 
      
    </div>      
    <button class="carousel-control-prev" type="button" data-bs-target="#demo<%= @restaurant.id %>" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#demo<%= @restaurant.id %>" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>   
    </button>
  </div>

  <!--------------------------------------restaurant detail----------------------------------------------->               
  <h3 class="fw-bolder mt-3"><%= @restaurant.name %></h2 >

  <div id="map"></div>
  <p class="text-muted"><%= @restaurant.full_address %></p>

  <div class="fst-italic" ><%= @restaurant.email %></div><br/>

    <span>categories:
    <% @restaurant.categories.each do |category| %>             
         <%= category.name %>         
    <% end %>  
    <span>
  <hr/>
  
  <!-----------------------------------map-------------------------------->
    <div class="col-12">
      <%= link_to google_map_restaurants_path do %>
       <%= image_tag ("icons8-google-maps-old.svg"), width: "30px", height: "30px" %>
       <% end %>
         &#160;&#160;

  <!--------------------------------Review button------------------------->  
      <div class="btn btn-danger">
        <span class="glyphicon glyphicon-star" aria-hidden="true"></span>                 
        <%= link_to "Add Review", new_restaurant_review_path(@restaurant),class: "review", data: { "bs-target": "#exampleModal", "bs-toggle": "modal", "bs-whatever": "@getbootstrap" } %>
      </div>   
      <br/>
      <br/>
    </div>
      
  <!------------------------------------Review--------------------------------------->
  
  <button id="review" class="mb-3 btn btn-danger" >Reviews</button>
     
  <div id="clicked">
    <div class="p">
      <%= render 'reviews/review' %>
    </div>  
  </div>

    <!------------------------------ Modal for reviews form ------------------------------------------------>
    <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLabel">Submit your Review</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
             <%= render 'reviews/form' %>   
        </div>
      </div>
    </div>

    <!-----------------------------------Restaurant Menu---------------------------------------->
      
    <%= link_to "Menu", restaurant_menus_path(@restaurant), class: "btn btn-outline-info btn-lg mb-3" %> 

    <div class="rounded">
      <%= link_to restaurant_menu_path(@restaurant.menus.ids), data: { "bs-target": "#staticBackdrop", "bs-toggle": "modal" } do %>
        <%= image_tag ("brooke-lark-V4MBq8kue3U-unsplash.jpg"), class: "rounded", width: "300px", height: "300px" %>
      <% end %>  
    </div>

    <!-----------------------------Restaurant Menu By dropdown-------------------------------------->

    <div class="modal fade" id="staticBackdrop" data-bs-backdrop="static" data-bs-keyboard="false" tabindex="-1" aria-labelledby="staticBackdropLabel" aria-hidden="true">
      <div class="modal-dialog modal-dialog-centered modal-dialog-scrollable">
        <div class="modal-content">
          <div class="modal-header">
            <h5 class="modal-title" id="staticBackdropLabel">Restaurant Menu</h5>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>
            <%= render 'menus/show' %> 
          <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
          </div>
        </div>
      </div>
    </div>

</div>


     

app/views/restaurants/update.js.erb
$("#newRestaurant").html("<%= j (render "index", restaurant: @restaurants) %>")